Reviews
I-Karpoff/vegans-dream pull request #1
Opened 2024-10-17 11:37 UTC by Tykhon01

2024-10-17 12:17 UTC, I-Karpoff commented on src/css/reviews.css
> +}
Готовые паддинги на вашу секцию уже есть в стилях base.css добавьте его, этот можно удалить

2024-10-17 12:20 UTC, I-Karpoff commented on src/css/reviews.css
> +}
Готовый контейнер так же есть в стилях container.css посмотрите

2024-10-17 12:35 UTC, I-Karpoff requested changes
Необходимо добавить 2х картинки, десктопную, планшетную версию, скрыть <li> в мобильной версии, сделать border. Так же удалите ваши картинки.ІІ

2024-10-17 13:07 UTC, I-Karpoff commented
Доработка кода

2024-10-18 12:27 UTC, Tykhon01 commented on src/css/reviews.css
> +}
+

2024-10-18 12:27 UTC, Tykhon01 commented on src/css/reviews.css
> +}
+

2024-10-18 16:20 UTC, closed without merging