vegetables section done
I-Karpoff/vegans-dream pull request #3
Opened 2024-10-17 16:00 UTC by 7empered

2024-10-17 16:11 UTC, I-Karpoff requested changes

2024-10-17 16:11 UTC, I-Karpoff commented on src/css/vegetables.css
> +
У нас есть общие стили с паддингами на секцию , задайте их этот можно удалить. Вторым задайте просто цвет фона тогда

2024-10-17 16:11 UTC, I-Karpoff commented on src/css/vegetables.css
> +
Тоже самое у нас общий стиль для паддинга

2024-10-17 16:11 UTC, I-Karpoff commented on src/css/vegetables.css
> +
Контейнер идёт общим стилем base.css

2024-10-17 16:11 UTC, I-Karpoff commented on src/css/vegetables.css
> +
16px по стандарту текст можно убрать

2024-10-17 16:11 UTC, I-Karpoff commented on src/css/vegetables.css
> +
Контейнер общий

2024-10-17 16:11 UTC, I-Karpoff commented on src/partials/vegetables.html
> +                     alt="picture of eggplant"
Пути к картинкам должны начинаться с тильды без точек

2024-10-17 16:18 UTC, 7empered commented on src/css/vegetables.css
> +
Коли залишаю контейнер незмінним, тобто з падінгом 20, то лішки відрізняються від макету, бо мають неправильний розмір.

2024-10-18 08:20 UTC, I-Karpoff approved these changes

2024-10-18 08:20 UTC, merged