full section Hero
I-Karpoff/vegans-dream pull request #5
Opened 2024-10-18 12:09 UTC by Aleksandr-1977

1. Прошу проверить правильность padding\margin в desktop версии по тексту. Не уверен, что правильно сделал. Хоть и отображает, как по макету.
2. Как будет размещаться Header, на моей секции?

2024-10-18 12:34 UTC, I-Karpoff requested changes
1. Отцентровать марджином на десктоп версии

2024-10-18 18:48 UTC, Aleksandr-1977 commented
Вроде все исправил.

2024-10-19 05:42 UTC, I-Karpoff requested changes
Удали в начале кода <br />hero section, так вроде все ОК, но есть один момент, контейнер должен тянуться как у всех по viewport , а он стоит на месте когда растягиваешь desktop версию

2024-10-19 08:11 UTC, I-Karpoff approved these changes

2024-10-19 08:11 UTC, merged